import type { MeetingSummary } from "@/types/meeting";

/** Format a meeting summary as markdown text for clipboard copying */
export function formatSummaryAsMarkdown(summary: MeetingSummary): string {
  return `
# ${summary.subject}
Date: ${new Date(summary.date).toLocaleDateString()}

## Summary
${summary.fullSummary}

## Key Decisions
${summary.keyDecisions.map((d) => `- ${d}`).join("\n")}

## Action Items
${summary.actionItems.map((a) => `- ${a.owner}: ${a.task}${a.deadline ? ` (Due: ${a.deadline})` : ""}`).join("\n")}

## Key Metrics
${summary.metrics.map((m) => `- ${m}`).join("\n")}

## Next Steps
${summary.nextSteps.map((s) => `- ${s}`).join("\n")}
  `.trim();
}

/** Format a meeting summary as HTML for email sharing */
export function formatSummaryAsHtml(summary: MeetingSummary): string {
  return `
<div style="font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; color: #333;">
  <h1 style="color: #1a1a1a; border-bottom: 2px solid #0078d4; padding-bottom: 10px;">Meeting Summary</h1>

  <div style="background-color: #f5f5f5; padding: 15px; border-radius: 8px; margin-bottom: 20px;">
    <h2 style="margin: 0 0 10px 0; color: #1a1a1a;">${summary.subject}</h2>
    <p style="margin: 0; color: #666;"><strong>Date:</strong> ${new Date(summary.date).toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}</p>
  </div>

  <div style="margin-bottom: 25px;">
    <h3 style="color: #0078d4; margin-bottom: 10px; border-bottom: 1px solid #ddd; padding-bottom: 5px;">Summary</h3>
    <p style="line-height: 1.6; white-space: pre-wrap;">${summary.fullSummary}</p>
  </div>

  ${summary.keyDecisions.length > 0 ? `
  <div style="margin-bottom: 25px;">
    <h3 style="color: #0078d4; margin-bottom: 10px; border-bottom: 1px solid #ddd; padding-bottom: 5px;">Key Decisions</h3>
    <ul style="line-height: 1.8; padding-left: 20px;">
      ${summary.keyDecisions.map(d => `<li style="margin-bottom: 8px;">${d}</li>`).join('')}
    </ul>
  </div>
  ` : ''}

  ${summary.actionItems.length > 0 ? `
  <div style="margin-bottom: 25px;">
    <h3 style="color: #0078d4; margin-bottom: 10px; border-bottom: 1px solid #ddd; padding-bottom: 5px;">Action Items</h3>
    <table style="width: 100%; border-collapse: collapse; margin-top: 10px;">
      <thead>
        <tr style="background-color: #f0f0f0;">
          <th style="text-align: left; padding: 10px; border: 1px solid #ddd; font-weight: 600;">Owner</th>
          <th style="text-align: left; padding: 10px; border: 1px solid #ddd; font-weight: 600;">Task</th>
          <th style="text-align: left; padding: 10px; border: 1px solid #ddd; font-weight: 600;">Due Date</th>
        </tr>
      </thead>
      <tbody>
        ${summary.actionItems.map(a => `
        <tr>
          <td style="padding: 10px; border: 1px solid #ddd; font-weight: 500;">${a.owner}</td>
          <td style="padding: 10px; border: 1px solid #ddd;">${a.task}</td>
          <td style="padding: 10px; border: 1px solid #ddd;">${a.deadline || 'Not specified'}</td>
        </tr>
        `).join('')}
      </tbody>
    </table>
  </div>
  ` : ''}

  ${summary.metrics.length > 0 ? `
  <div style="margin-bottom: 25px;">
    <h3 style="color: #0078d4; margin-bottom: 10px; border-bottom: 1px solid #ddd; padding-bottom: 5px;">Key Metrics</h3>
    <ul style="line-height: 1.8; padding-left: 20px;">
      ${summary.metrics.map(m => `<li style="margin-bottom: 8px;">${m}</li>`).join('')}
    </ul>
  </div>
  ` : ''}

  ${summary.nextSteps.length > 0 ? `
  <div style="margin-bottom: 25px;">
    <h3 style="color: #0078d4; margin-bottom: 10px; border-bottom: 1px solid #ddd; padding-bottom: 5px;">Next Steps</h3>
    <ul style="line-height: 1.8; padding-left: 20px;">
      ${summary.nextSteps.map(s => `<li style="margin-bottom: 8px;">${s}</li>`).join('')}
    </ul>
  </div>
  ` : ''}

  <hr style="border: none; border-top: 1px solid #ddd; margin: 30px 0;" />
  <p style="color: #888; font-size: 12px; text-align: center;">
    <em>This summary was generated by the Meeting Summarizer app.</em>
  </p>
</div>
  `.trim();
}
